### ISSUE TITLE
Add a conflict type to stone

### ISSUE THREAD

**Issue by ikeycode** [serpent-os/tools#39]
Conflict will essentially be identical to Dependency/Provider, allowing us to conflict with a specific type of identity.

Sidequest:

 - Extend DAG/layering to handle conflict resolution
 - Perhaps a time to investigate eopkg-style replaces?

**Comment by GZGavinZhao** [comment]
Working on `autobuild` right now but I want to come back to this at a later date, so writing in case I forget.

Detecting and outputting conflicts is a 2-SAT problem and can be done in `O(N + M)` time where `N` is the number of packages and `M` is the number of dependency relations. The only graph algorithm I need is the ability to form a strongly connected component, which `petgraph` does provide so I believe this is doable.

I haven't come up with a way to output the conflict between providers. In other words, in my current design, when a conflict happens, all I can do is to say hey surprise package `X` conflicts with packages `Y`, `Z`, ... I haven't figured out a way to say provider `bin(X)` conflicts with providers `soname(liby)` and `name(Z)`.

**Comment by ermo** [comment]
Added in https://github.com/serpent-os/tools/pull/248
